version: '3'
services:
  service-a:
    build: ./serviceA
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
  service-b:
    build: ./serviceB
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
