version: '3'
services:
  service-a:
    build: ./serviceA # Path to the service-A service
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
